"""
Info about the file structure
    Creates the dictionary file_info that contains all information. All information stored
    in the dictionary can then easily be addressed using the keys listed below.

    'data_timestamp_col':       Index of the timestamp column in the file. In this example
                                the timestamp is in the first column (index 0).

    'data_timestamp_format':    The format of the current timestamp, as stored to the file
                                by the logger. In this example the timestamp in the first column
                                looks like this: "2018-08-15 00:00:00". When reading the file,
                                the double quotes around the timestamp are ignored.

    'data_header_rows':         The CR1000 header



    'file_LN':                  LN (2 digits) is the logger number (each logger must be identified
                                by a unique number)

    'file_FN':                  FN (2 digits) is the number of the file generated by the logger

    Abbreviations: d ... data, f ... file, fn ... filename


"""
from pathlib import Path


def f_10_meteo():
    # example filename: CH-DAV_iDL_T1_35_1_TBL1_2018_08_17_0000.dat

    file_info = {
        'd_timestamp_col': 0,
        'd_timestamp_format': '%Y-%m-%d %H:%M:%S',
        'd_icos_timestamp_format': '%Y%m%d%H%M%S',
        'd_timestamp_keep_non_icos': True,
        'd_header_rows': [1, 2],
        'd_header_row_with_variable_names': 1,
        'd_header_remove_suffix_from_variable_names': [],
        'd_header_output_to_file': True,
        'd_skip_rows': [3],
        'd_separator': ',',
        'd_rename_columns': False,
        'd_keep_only_renamed_columns': False,
        'd_only_most_recent_day': False,
        'fname_generate_icos_filename': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'fname_year_position': [24, 28],
        'fname_month_position': [29, 31],
        'fname_day_position': [32, 34],
        'fname_hour_position': [35, 37],
        'fname_minute_position': [37, 39],
        'fname_length': 43,
        'fname_id': 'CH-DAV_iDL_T1_35_1_TBL1_*.dat',
        'f_type': '10_meteo',
        'f_resolution': '10S',
        'f_LN': '02',
        'f_FN': '03',
        'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/10_meteo'),
        # 'f_source_dir': 'input',
        'f_log_subdir': Path('logs'),
        'icos_file_outpath': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/10_meteo'),
        # 'icos_file_outpath': Path('output/10_meteo'),
        'f_compression': True,
        'f_delete_uncompressed': True
    }

    return file_info


def f_10_meteo_heatflag_sonic():
    # example filename: CH-DAV_iDL_T1_35_1_TBL1_2018_08_17_0000.dat

    file_info = {
        'd_timestamp_col': 0,
        'd_timestamp_format': '%Y-%m-%d %H:%M:%S',
        'd_icos_timestamp_format': '%Y%m%d%H%M',
        'd_timestamp_keep_non_icos': False,
        'd_header_rows': [1, 2],
        'd_header_row_with_variable_names': 1,
        'd_header_remove_suffix_from_variable_names': [],
        'd_header_output_to_file': False,
        'd_skip_rows': [3],
        'd_separator': ',',
        'd_rename_columns': False,
        'd_keep_only_renamed_columns': False,
        'd_only_most_recent_day': False,
        'fname_generate_icos_filename': 'CH-Dav_SAHEAT_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'fname_year_position': [24, 28],
        'fname_month_position': [29, 31],
        'fname_day_position': [32, 34],
        'fname_hour_position': [35, 37],
        'fname_minute_position': [37, 39],
        'fname_length': 43,
        'fname_id': 'CH-DAV_iDL_T1_35_1_TBL2_*.dat',
        'f_type': '10_meteo_heatflag_sonic',
        'f_resolution': '1T',
        'f_LN': '02',
        'f_FN': '02',
        # 'f_source_dir': Path('input'),Y:\CH-DAV_Davos\01_ICOS_TRANSFER
        'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/10_meteo'),
        # 'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/10_meteo/2018/09'),
        'f_log_subdir': Path('log'),
        'icos_file_outpath': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/10_meteo_heatflag_sonic'),
        # 'icos_file_outpath': Path('output/10_meteo_heatflag_sonic'),
        'f_compression': False,
        'f_delete_uncompressed': False
    }

    return file_info


def f_12_meteo_forest_floor(forest_floor, table):
    # For forest floor data files, some settings are created dynamically b/c we have different files,
    # i.e. forest floors 1-5 and each have tables 1 and 2 (total 10 files)
    # example filename: CH-DAV_iDL_FF1_0_1_TBL1_2018_08_19_0000.dat

    file_info = {
        'd_timestamp_col': 0,
        'd_timestamp_format': '%Y-%m-%d %H:%M:%S',
        'd_icos_timestamp_format': '%Y%m%d%H%M',
        'd_timestamp_keep_non_icos': True,
        'd_header_rows': [1, 2],
        'd_header_row_with_variable_names': 1,
        'd_header_remove_suffix_from_variable_names': ['_Avg'],
        'd_header_output_to_file': True,
        'd_skip_rows': [3],
        'd_separator': ',',
        'd_rename_columns': False,
        'd_keep_only_renamed_columns': False,
        'd_only_most_recent_day': False,
        'fname_generate_icos_filename': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'fname_year_position': [24, 28],
        'fname_month_position': [29, 31],
        'fname_day_position': [32, 34],
        'fname_hour_position': [35, 37],
        'fname_minute_position': [37, 39],
        'fname_length': 43,
        # 'f_source_dir': Path('input'),
        'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/12_meteo_forestfloor'),
        'f_log_subdir': Path('log'),
        'icos_file_outpath': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/12_meteo_forestfloor'),
        # 'icos_file_outpath': Path('output/12_meteo_forestfloor'),
        'f_compression': True,
        'f_delete_uncompressed': True
    }

    file_info['fname_id'] = 'CH-DAV_iDL_FF{ff}_0_1_TBL{t}_*.dat'.format(ff=forest_floor, t=table)
    file_info['f_type'] = '12_meteo_forest_floor_FF{ff}_TBL{t}'.format(ff=forest_floor, t=table)

    # ICOS file and logger numbers

    # FN ICOS file numbers
    # Changed in v4.0.7: conditional 'if' for each FF and their respective file number,
    # necessary due to updates in F01 for FF1-5 --> they have now F03 but could have
    # file numbers different from each other in the future.
    if table == 1:
        file_info['f_resolution'] = '1T'
        if forest_floor == 1:
            file_info['f_FN'] = '04'
        elif forest_floor == 2:
            file_info['f_FN'] = '04'
        elif forest_floor == 3:
            file_info['f_FN'] = '04'
        elif forest_floor == 4:
            file_info['f_FN'] = '03'
        elif forest_floor == 5:
            file_info['f_FN'] = '03'

    # LN ICOS logger numbers
    if forest_floor == 1:
        file_info['f_LN'] = '04'
    elif forest_floor == 2:
        file_info['f_LN'] = '05'
    elif forest_floor == 3:
        file_info['f_LN'] = '06'
    elif forest_floor == 4:
        file_info['f_LN'] = '07'
    elif forest_floor == 5:
        file_info['f_LN'] = '08'

    return file_info


def f_13_meteo_meteoswiss():
    """
    Parameters in the file as sent by MeteoSwiss:
    tre200s0    °C      Lufttemperatur 2 m über Boden; Momentanwert
    gre000z0    W/m²    Globalstrahlung; Zehnminutenmittel
    rre150z0    mm      Niederschlag; Zehnminutensumme
    ure200s0    %       Relative Luftfeuchtigkeit 2 m über Boden; Momentanwert
    """

    # example filename: VQAA77.201809030525

    # in case column names need to be changed, new names are defined here
    renaming_map = {
        'tre200s0': 'TA_3_1_1',
        'gre000z0': 'SW_IN_3_1_1',
        'rre150z0': 'P_3_1_1',
        'ure200s0': 'RH_3_1_1'
    }

    file_info = {
        'd_timestamp_col': 1,
        'd_timestamp_format': '%Y%m%d%H%M',
        'd_icos_timestamp_format': '%Y%m%d%H%M%S',
        'd_timestamp_keep_non_icos': True,
        'd_header_rows': [0],
        'd_header_row_with_variable_names': 0,
        'd_header_remove_suffix_from_variable_names': [],
        'd_header_output_to_file': True,
        'd_skip_rows': None,
        'd_separator': ';',
        'd_rename_columns': renaming_map,
        'd_keep_only_renamed_columns': False,
        'd_only_most_recent_day': True,
        'fname_generate_icos_filename': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'fname_year_position': [7, 11],
        'fname_month_position': [11, 13],
        'fname_day_position': [13, 15],
        'fname_hour_position': [15, 17],
        'fname_minute_position': [17, 18],
        'fname_length': 19,
        'fname_id': 'VQAA77.*',
        'f_type': '13_meteo_meteoswiss',
        'f_resolution': '10T',
        'f_LN': '20',
        'f_FN': '02',
        'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/13_meteo_meteoswiss'),
        'f_log_subdir': Path('log'),
        'icos_file_outpath': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/13_meteo_meteoswiss'),
        # 'icos_file_outpath': Path('output/13_meteo_meteoswiss'),
        'f_compression': True,
        'f_delete_uncompressed': True
    }

    return file_info


def f_13_meteo_backup_eth():
    # This file is now only logging data for SW_IN
    # example filename: CH-DAV_iDL_T1_35_2_TBL1_2018_09_29_0100.dat

    file_info = {
        'd_timestamp_col': 0,
        'd_timestamp_format': '%Y-%m-%d %H:%M:%S',
        'd_icos_timestamp_format': '%Y%m%d%H%M%S',
        'd_timestamp_keep_non_icos': True,
        'd_header_rows': [1, 2],
        'd_header_row_with_variable_names': 1,
        'd_header_remove_suffix_from_variable_names': [],
        'd_header_output_to_file': True,
        'd_skip_rows': [3],
        'd_separator': ',',
        'd_rename_columns': False,
        'd_keep_only_renamed_columns': False,
        'd_only_most_recent_day': False,
        'fname_generate_icos_filename': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'fname_year_position': [24, 28],
        'fname_month_position': [29, 31],
        'fname_day_position': [32, 34],
        'fname_hour_position': [35, 37],
        'fname_minute_position': [37, 39],
        'fname_length': 43,
        'fname_id': 'CH-DAV_iDL_T1_35_2_TBL1_*.dat',
        'f_type': '13_meteo_backup_eth',
        'f_resolution': '10S',
        'f_LN': '21',
        'f_FN': '04',
        'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/13_meteo_backup_eth'),
        # 'f_source_dir': Path('input'),
        'f_log_subdir': Path('logs'),
        # 'f_log_subdir': 'logs',
        'icos_file_outpath': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/13_meteo_backup_eth'),
        # 'icos_file_outpath': Path('output/13_meteo_backup_eth'),
        'f_compression': True,
        'f_delete_uncompressed': True
    }

    return file_info


def f_13_meteo_nabel():
    # example filename: DAV_Meteo_NABEL_181023.CSV

    # problem: file rows have trailing semi-colon at the end
    # http://wesmckinney.com/blog/update-on-upcoming-pandas-v0-10-new-file-parser-other-performance-wins/

    # in case column names need to be changed, new names are defined here
    renaming_map = {
        'TEMP': 'TA_1_6_2',
        'FEUCHT': 'RH_1_6_2',
        'REGEN': 'P_1_1_1',
        # 'STRGLO': 'SW_IN_1_1_3'  # todo not used, low resolution, instead used from hut logger w/ higher resolution
    }

    file_info = {
        'd_timestamp_col': 0,
        'd_timestamp_format': '%d.%m.%Y %H:%M',
        'd_icos_timestamp_format': '%Y%m%d%H%M%S',
        'd_timestamp_keep_non_icos': True,
        'd_header_rows': [1],
        'd_header_row_with_variable_names': 1,
        'd_header_remove_suffix_from_variable_names': [],
        'd_header_output_to_file': True,
        'd_skip_rows': [2, 3],
        'd_separator': ';',
        'd_rename_columns': renaming_map,
        'd_keep_only_renamed_columns': True,
        'd_only_most_recent_day': True,
        'fname_generate_icos_filename': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'fname_year_position': [16, 18],
        'fname_month_position': [18, 20],
        'fname_day_position': [20, 22],
        'fname_hour_position': [],
        'fname_minute_position': [],
        'fname_length': 26,
        'fname_id': 'DAV_Meteo_NABEL_*.CSV',
        'f_type': '13_meteo_nabel',
        'f_resolution': '60S',
        'f_LN': '22',
        'f_FN': '03',
        'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/13_meteo_nabel'),
        # 'f_source_dir': Path('input'),
        'f_log_subdir': Path('logs'),
        # 'f_log_subdir': 'logs',
        'icos_file_outpath': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/13_meteo_nabel'),
        # 'icos_file_outpath': Path('output/13_meteo_backup_eth'),
        'f_compression': True,
        'f_delete_uncompressed': True
    }

    return file_info

def f_15_meteo_snowheight():
    # Current: edited 2022-01-05, LH
    # first file with this format 2021-12-02
    # - TOA5
    # - example filename: CH-DAV_snowheight_20220104.dat
    # - file now stores ETH variable names that are then
    #   renamed to ICOS variable names with this script

    renaming_map = {
        'D_SNOW_M1_1.8_1_Smp': 'D_SNOW_1_1_1',
        'TA_M1_1.8_1_Smp': 'TA_M1_1.8_1_Smp',
        'QUALITY_iSR50AT_M1_1.8_1_Smp': 'QUALITY_iSR50AT_M1_1.8_1_Smp',
        'DIAG_iSR50AT_M1_1.8_1_Smp': 'DIAG_iSR50AT_M1_1.8_1_Smp'
    }

    file_info = {
        'd_timestamp_col': 0,
        'd_timestamp_format': '%Y-%m-%d %H:%M:%S',  # 2022-01-05
        'd_icos_timestamp_format': '%Y%m%d%H%M%S',
        'd_timestamp_keep_non_icos': True,
        'd_header_rows': [1, 2],  # 2022-01-05
        'd_header_row_with_variable_names': 1,  # 2022-01-05
        'd_header_remove_suffix_from_variable_names': [],
        'd_header_output_to_file': True,
        'd_skip_rows': [3],  # 2022-05-01
        'd_separator': ',',
        'd_rename_columns': renaming_map,  # 2022-01-05
        'd_keep_only_renamed_columns': False,
        'd_only_most_recent_day': False,
        'fname_generate_icos_filename': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'fname_year_position': [18, 22],  # 2022-01-05
        'fname_month_position': [22, 24],  # 2022-01-05
        'fname_day_position': [24, 26],  # 2022-01-05
        'fname_hour_position': [],
        'fname_minute_position': [],
        'fname_length': 30,
        'fname_id': 'CH-DAV_snowheight_*.dat',  # 2022-01-05
        'f_type': '15_meteo_snowheight',  # 2022-01-05
        'f_resolution': '1T',
        'f_LN': '01',
        'f_FN': '07',  # 2022-01-05
        'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/15_meteo_snowheight'),
        'f_log_subdir': Path('logs'),
        'icos_file_outpath': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/15_meteo_snowheight'),
        'f_compression': True,
        'f_delete_uncompressed': True
    }

    # previous format ending 2021-12-01:
    # (deprecated) example filename: CH-Dav_BM_20211031_L01_F06.dat
    # 'd_timestamp_format': '%Y%m%d%H%M%S',
    # 'd_header_rows': [0],
    # 'd_rename_columns': False,
    # 'd_header_row_with_variable_names': 0,
    # 'd_skip_rows': [],
    # 'fname_year_position': [10, 14],
    # 'fname_month_position': [14, 16],
    # 'fname_day_position': [16, 18],
    # 'fname_id': 'CH-Dav_BM_*_L01_F06.dat',
    # 'f_type': '10_meteo',
    # 'f_FN': '06',

    return file_info



def f_17_meteo_profile():
    # example filename: CH-Dav_BM_20180819_L01_F02.dat

    file_info = {
        'd_timestamp_col': 0,
        'd_timestamp_format': '%Y%m%d%H%M%S',
        'd_icos_timestamp_format': '%Y%m%d%H%M%S',
        'd_timestamp_keep_non_icos': True,
        'd_header_rows': [0],
        'd_header_row_with_variable_names': 0,
        'd_header_remove_suffix_from_variable_names': [],
        'd_header_output_to_file': True,
        'd_skip_rows': None,
        'd_separator': ',',
        'd_rename_columns': False,
        'd_keep_only_renamed_columns': False,
        'd_only_most_recent_day': False,
        'fname_generate_icos_filename': False,
        'fname_year_position': [10, 14],
        'fname_month_position': [14, 16],
        'fname_day_position': [16, 18],
        'fname_hour_position': [],
        'fname_minute_position': [],
        'fname_length': 30,
        'fname_id': 'CH-Dav_BM_*_L01_F02.dat',
        'f_type': '17_meteo_profile',
        'f_resolution': '10S',
        'f_LN': '01',
        'f_FN': '02',
        'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/17_meteo_profile'),
        'f_log_subdir': Path('log'),
        'icos_file_outpath': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/17_meteo_profile'),
        # 'icos_file_outpath': Path('output/17_meteo_profile'),
        'f_compression': True,
        'f_delete_uncompressed': True
    }

    return file_info


def f_30_profile_ghg():
    file_info = {
        'd_timestamp_col': 0,
        'd_timestamp_format': '%Y%m%d%H%M%S',
        'd_icos_timestamp_format': '%Y%m%d%H%M%S',
        'd_timestamp_keep_non_icos': True,
        'd_header_rows': [0],
        'd_header_row_with_variable_names': 0,
        'd_header_remove_suffix_from_variable_names': [],
        'd_header_output_to_file': True,
        'd_skip_rows': None,
        'd_separator': ',',
        'd_rename_columns': False,
        'd_keep_only_renamed_columns': False,
        'd_only_most_recent_day': False,
        # todo the next line should be set to empty [] once PM has changed the filename
        'fname_generate_icos_filename': 'CH-Dav_ST_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        # 'fname_generate_icos_filename': False,
        'fname_year_position': [10, 14],
        'fname_month_position': [14, 16],
        'fname_day_position': [16, 18],
        'fname_hour_position': [],
        'fname_minute_position': [],
        'fname_length': 30,
        'fname_id': 'CH-Dav_ST_*_L10_F01.dat',
        'f_type': '30_profile_ghg',
        'f_resolution': '1S',
        'f_LN': '10',
        'f_FN': '02',  # renamed to correct ICOS file number
        'f_source_dir': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/30_profile_ghg'),
        # 'f_source_dir': 'input',
        'f_log_subdir': Path('logs'),
        'icos_file_outpath': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/30_profile_ghg'),
        # 'icos_file_outpath': Path('output/30_profile_ghg'),
        'f_compression': True,
        'f_delete_uncompressed': True
    }

    return file_info
