"""
Info about the file structure
    Creates the dictionary file_info that contains all information. All information stored
    in the dictionary can then easily be addressed using the keys listed below.

    'data_timestamp_col':       Index of the timestamp column in the file. In this example
                                the timestamp is in the first column (index 0).

    'data_timestamp_format':    The format of the current timestamp, as stored to the file
                                by the logger. In this example the timestamp in the first column
                                looks like this: "2018-08-15 00:00:00". When reading the file,
                                the double quotes around the timestamp are ignored.

    'data_header_rows':         The CR1000 header

    'file_LN':                  LN (2 digits) is the logger number (each logger must be identified
                                by a unique number)

    'file_FN':                  FN (2 digits) is the number of the file generated by the logger

    Abbreviations: d ... data, f ... file, fn ... filename


"""
from pathlib import Path


def f_10_meteo():
    # example filename: CH-DAV_iDL_T1_35_1_TBL1_2018_08_17_0000.dat

    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': False,
        'DATA_FREQUENCY': '10S',
        'DATA_HEADER_OUTPUT_TO_FILE': True,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': [],
        'DATA_HEADER_ROWS': [1, 2],
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': False,
        'DATA_RENAME_COLUMNS': False,
        'DATA_SEPARATOR': ',',
        'DATA_SKIP_ROWS': [3],
        'DATA_TIMESTAMP_COL': 0,
        'DATA_TIMESTAMP_FORMAT': '%Y-%m-%d %H:%M:%S',
        'DATA_TIMESTAMP_KEEP_NON_ICOS': True,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/10_meteo'),
        'DIR_OUT_LOGFILE': Path('logs'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/10_meteo'),
        'FILE_FILEGROUP': '10_meteo',
        'FILENAME_DAY_POSITION': [32, 34],
        'FILENAME_FOR_ICOS': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [35, 37],
        'FILENAME_ID': 'CH-DAV_iDL_T1_35_1_TBL1_*.dat',
        'FILENAME_LENGTH': 43,
        'FILENAME_MINUTE_POSITION': [37, 39],
        'FILENAME_MONTH_POSITION': [29, 31],
        'FILENAME_YEAR_POSITION': [24, 28],
        'OUTFILE_COMPRESSION': True,
        'OUTFILE_DELETE_UNCOMPRESSED': True,
        'OUTFILE_ICOS_FILENUMBER_FN': '03',
        'OUTFILE_ICOS_LOGGERNUMBER_LN': '02'
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\10_meteo'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\10_meteo')  # testing
    }

    return file_info


def f_10_meteo_heatflag_sonic():
    # example filename: CH-DAV_iDL_T1_35_1_TBL1_2018_08_17_0000.dat

    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': False,
        'DATA_FREQUENCY': '1T',
        'DATA_HEADER_OUTPUT_TO_FILE': False,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': [],
        'DATA_HEADER_ROWS': [1, 2],
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': False,
        'DATA_RENAME_COLUMNS': False,
        'DATA_SEPARATOR': ',',
        'DATA_SKIP_ROWS': [3],
        'DATA_TIMESTAMP_COL': 0,
        'DATA_TIMESTAMP_FORMAT': '%Y-%m-%d %H:%M:%S',
        'DATA_TIMESTAMP_KEEP_NON_ICOS': False,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/10_meteo_heatflag_sonic'),
        'DIR_OUT_LOGFILE': Path('log'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/10_meteo'),
        'FILE_FILEGROUP': '10_meteo_heatflag_sonic',
        'FILENAME_DAY_POSITION': [32, 34],
        'FILENAME_FOR_ICOS': 'CH-Dav_SAHEAT_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [35, 37],
        'FILENAME_ID': 'CH-DAV_iDL_T1_35_1_TBL2_*.dat',
        'FILENAME_LENGTH': 43,
        'FILENAME_MINUTE_POSITION': [37, 39],
        'FILENAME_MONTH_POSITION': [29, 31],
        'FILENAME_YEAR_POSITION': [24, 28],
        'OUTFILE_COMPRESSION': False,
        'OUTFILE_DELETE_UNCOMPRESSED': False,
        'OUTFILE_ICOS_FILENUMBER_FN': '02',
        'OUTFILE_ICOS_LOGGERNUMBER_LN': '02'
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\10_meteo'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\10_meteo_heatflag_sonic')  # testing
    }

    return file_info


def f_11_meteo_hut_prec():
    # File contains precipitation
    # example filename: CH-DAV_iDL_H1_0_1_TBL3_2023_01_25_0004.dat
    # Added in v4.0.14

    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': True,  # Some data of current day is stored in previous day's data
        'DATA_FREQUENCY': '1T',
        'DATA_HEADER_OUTPUT_TO_FILE': True,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': ['_Tot'],
        'DATA_HEADER_ROWS': [1, 2],
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': False,
        'DATA_RENAME_COLUMNS': False,
        'DATA_SEPARATOR': ',',
        'DATA_SKIP_ROWS': [3],
        'DATA_TIMESTAMP_COL': 0,
        'DATA_TIMESTAMP_FORMAT': '%Y-%m-%d %H:%M:%S',
        'DATA_TIMESTAMP_KEEP_NON_ICOS': True,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/11_meteo_hut'),
        'DIR_OUT_LOGFILE': Path('log'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/11_meteo_hut'),
        'FILE_FILEGROUP': '11_meteo_hut_prec',
        'FILENAME_DAY_POSITION': [31, 33],
        'FILENAME_FOR_ICOS': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [34, 36],
        'FILENAME_ID': 'CH-DAV_iDL_H1_0_1_TBL3_*.dat',
        'FILENAME_LENGTH': 42,
        'FILENAME_MINUTE_POSITION': [36, 38],
        'FILENAME_MONTH_POSITION': [28, 30],
        'FILENAME_YEAR_POSITION': [23, 27],
        'OUTFILE_COMPRESSION': True,
        'OUTFILE_DELETE_UNCOMPRESSED': True,
        'OUTFILE_ICOS_FILENUMBER_FN': '03',
        'OUTFILE_ICOS_LOGGERNUMBER_LN': '03'
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\11_meteo_hut'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\11_meteo_hut')  # testing
    }

    return file_info


def f_12_meteo_forest_floor(forest_floor, table):
    # For forest floor data files, some settings are created dynamically b/c we have different files,
    # i.e. forest floors 1-5 and each have tables 1 and 2 (total 10 files)
    # example filename: CH-DAV_iDL_FF1_0_1_TBL1_2018_08_19_0000.dat

    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': False,
        'DATA_HEADER_OUTPUT_TO_FILE': True,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': ['_Avg'],
        'DATA_HEADER_ROWS': [1, 2],
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': False,
        'DATA_RENAME_COLUMNS': False,
        'DATA_SEPARATOR': ',',
        'DATA_SKIP_ROWS': [3],
        'DATA_TIMESTAMP_COL': 0,
        'DATA_TIMESTAMP_FORMAT': '%Y-%m-%d %H:%M:%S',
        'DATA_TIMESTAMP_KEEP_NON_ICOS': True,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/12_meteo_forestfloor'),
        'DIR_OUT_LOGFILE': Path('log'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/12_meteo_forestfloor'),
        'FILENAME_DAY_POSITION': [32, 34],
        'FILENAME_FOR_ICOS': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [35, 37],
        'FILENAME_LENGTH': 43,
        'FILENAME_MINUTE_POSITION': [37, 39],
        'FILENAME_MONTH_POSITION': [29, 31],
        'FILENAME_YEAR_POSITION': [24, 28],
        'OUTFILE_COMPRESSION': True,
        'OUTFILE_DELETE_UNCOMPRESSED': True
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\12_meteo_forestfloor'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\12_meteo_forestfloor')  # testing
    }

    file_info['FILENAME_ID'] = 'CH-DAV_iDL_FF{ff}_0_1_TBL{t}_*.dat'.format(ff=forest_floor, t=table)
    file_info['FILE_FILEGROUP'] = '12_meteo_forest_floor_FF{ff}_TBL{t}'.format(ff=forest_floor, t=table)

    # ICOS file and logger numbers

    # FN ICOS file numbers
    # Changed in v4.0.7: conditional 'if' for each FF and their respective file number,
    # necessary due to updates in F01 for FF1-5 --> they have now F03 but could have
    # file numbers different from each other in the future.
    if table == 1:
        file_info['DATA_FREQUENCY'] = '1T'
        if forest_floor == 1:
            file_info['OUTFILE_ICOS_FILENUMBER_FN'] = '04'
        elif forest_floor == 2:
            file_info['OUTFILE_ICOS_FILENUMBER_FN'] = '04'
        elif forest_floor == 3:
            file_info['OUTFILE_ICOS_FILENUMBER_FN'] = '04'
        elif forest_floor == 4:
            file_info['OUTFILE_ICOS_FILENUMBER_FN'] = '03'
        elif forest_floor == 5:
            file_info['OUTFILE_ICOS_FILENUMBER_FN'] = '03'

    # LN ICOS logger numbers
    if forest_floor == 1:
        file_info['OUTFILE_ICOS_LOGGERNUMBER_LN'] = '04'
    elif forest_floor == 2:
        file_info['OUTFILE_ICOS_LOGGERNUMBER_LN'] = '05'
    elif forest_floor == 3:
        file_info['OUTFILE_ICOS_LOGGERNUMBER_LN'] = '06'
    elif forest_floor == 4:
        file_info['OUTFILE_ICOS_LOGGERNUMBER_LN'] = '07'
    elif forest_floor == 5:
        file_info['OUTFILE_ICOS_LOGGERNUMBER_LN'] = '08'

    return file_info


def f_13_meteo_meteoswiss():
    """
    Parameters in the file as sent by MeteoSwiss:
    tre200s0    °C      Lufttemperatur 2 m über Boden; Momentanwert
    gre000z0    W/m²    Globalstrahlung; Zehnminutenmittel
    rre150z0    mm      Niederschlag; Zehnminutensumme
    ure200s0    %       Relative Luftfeuchtigkeit 2 m über Boden; Momentanwert
    """

    # example filename: VQAA77.201809030525

    # in case column names need to be changed, new names are defined here
    renaming_map = {
        'tre200s0': 'TA_3_1_1',
        'gre000z0': 'SW_IN_3_1_1',
        'rre150z0': 'P_3_1_1',
        'ure200s0': 'RH_3_1_1'
    }

    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': False,
        'DATA_FREQUENCY': '10T',
        'DATA_HEADER_OUTPUT_TO_FILE': True,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': [],
        'DATA_HEADER_ROWS': [0],
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': False,
        'DATA_RENAME_COLUMNS': renaming_map,
        'DATA_SEPARATOR': ';',
        'DATA_SKIP_ROWS': None,
        'DATA_TIMESTAMP_COL': 1,
        'DATA_TIMESTAMP_FORMAT': '%Y%m%d%H%M',
        'DATA_TIMESTAMP_KEEP_NON_ICOS': True,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/13_meteo_meteoswiss'),
        'DIR_OUT_LOGFILE': Path('log'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/13_meteo_meteoswiss'),
        'FILE_FILEGROUP': '13_meteo_meteoswiss',
        'FILENAME_DAY_POSITION': [13, 15],
        'FILENAME_FOR_ICOS': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [15, 17],
        'FILENAME_ID': 'VQAA77.*',
        'FILENAME_LENGTH': 19,
        'FILENAME_MINUTE_POSITION': [17, 18],
        'FILENAME_MONTH_POSITION': [11, 13],
        'FILENAME_YEAR_POSITION': [7, 11],
        'OUTFILE_COMPRESSION': True,
        'OUTFILE_DELETE_UNCOMPRESSED': True,
        'OUTFILE_ICOS_FILENUMBER_FN': '02',
        'OUTFILE_ICOS_LOGGERNUMBER_LN': '20'
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\13_meteo_meteoswiss'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\13_meteo_meteoswiss')  # testing
    }

    return file_info


def f_13_meteo_backup_eth():
    # This file is now only logging data for SW_IN
    # example filename: CH-DAV_iDL_T1_35_2_TBL1_2018_09_29_0100.dat

    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': False,
        'DATA_FREQUENCY': '10S',
        'DATA_HEADER_OUTPUT_TO_FILE': True,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': [],
        'DATA_HEADER_ROWS': [1, 2],
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': False,
        'DATA_RENAME_COLUMNS': False,
        'DATA_SEPARATOR': ',',
        'DATA_SKIP_ROWS': [3],
        'DATA_TIMESTAMP_COL': 0,
        'DATA_TIMESTAMP_FORMAT': '%Y-%m-%d %H:%M:%S',
        'DATA_TIMESTAMP_KEEP_NON_ICOS': True,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/13_meteo_backup_eth'),
        'DIR_OUT_LOGFILE': Path('logs'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/13_meteo_backup_eth'),
        'FILE_FILEGROUP': '13_meteo_backup_eth',
        'FILENAME_DAY_POSITION': [32, 34],
        'FILENAME_FOR_ICOS': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [35, 37],
        'FILENAME_ID': 'CH-DAV_iDL_T1_35_2_TBL1_*.dat',
        'FILENAME_LENGTH': 43,
        'FILENAME_MINUTE_POSITION': [37, 39],
        'FILENAME_MONTH_POSITION': [29, 31],
        'FILENAME_YEAR_POSITION': [24, 28],
        'OUTFILE_COMPRESSION': True,
        'OUTFILE_DELETE_UNCOMPRESSED': True,
        'OUTFILE_ICOS_FILENUMBER_FN': '04',
        'OUTFILE_ICOS_LOGGERNUMBER_LN': '21'
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\13_meteo_backup_eth'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\13_meteo_backup_eth')  # testing
    }

    return file_info


def f_13_meteo_nabel():
    # example filename: DAV_Meteo_NABEL_181023.CSV

    # problem: file rows have trailing semicolon at the end
    # http://wesmckinney.com/blog/update-on-upcoming-pandas-v0-10-new-file-parser-other-performance-wins/

    # in case column names need to be changed, new names are defined here
    renaming_map = {
        'TEMP': 'TA_1_6_2',
        'FEUCHT': 'RH_1_6_2',
        # Changed in v4.1
        # 'REGEN' not needed, data not correct, instead 11_meteo_hut TBL3 is used for precip at 1MIN,
        # 'REGEN': 'P_1_1_1',
        # 'STRGLO': 'SW_IN_1_1_3'  # todo not used, low resolution, instead used from hut logger w/ higher resolution
    }

    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': False,
        'DATA_FREQUENCY': '60S',
        'DATA_HEADER_OUTPUT_TO_FILE': True,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': [],
        'DATA_HEADER_ROWS': [1],
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': True,
        'DATA_RENAME_COLUMNS': renaming_map,
        'DATA_SEPARATOR': ';',
        'DATA_SKIP_ROWS': [2, 3],
        'DATA_TIMESTAMP_COL': 0,
        'DATA_TIMESTAMP_FORMAT': '%d.%m.%Y %H:%M',
        'DATA_TIMESTAMP_KEEP_NON_ICOS': True,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/13_meteo_nabel'),
        'DIR_OUT_LOGFILE': Path('logs'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/13_meteo_nabel'),
        'FILE_FILEGROUP': '13_meteo_nabel',
        'FILENAME_DAY_POSITION': [20, 22],
        'FILENAME_FOR_ICOS': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [],
        'FILENAME_ID': 'DAV_Meteo_NABEL_*.CSV',
        'FILENAME_LENGTH': 26,
        'FILENAME_MINUTE_POSITION': [],
        'FILENAME_MONTH_POSITION': [18, 20],
        'FILENAME_YEAR_POSITION': [16, 18],
        'OUTFILE_COMPRESSION': True,
        'OUTFILE_DELETE_UNCOMPRESSED': True,
        'OUTFILE_ICOS_FILENUMBER_FN': '04',  # Updated F03 --> F04 in v4.1
        'OUTFILE_ICOS_LOGGERNUMBER_LN': '22'
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\13_meteo_nabel'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\13_meteo_nabel')  # testing
    }

    return file_info


def f_15_meteo_snowheight():
    # Current: edited 2022-01-05, LH
    # first file with this format 2021-12-02
    # - TOA5
    # - example filename: CH-DAV_snowheight_20220104.dat
    # - file now stores ETH variable names that are then
    #   renamed to ICOS variable names with this script

    renaming_map = {
        'D_SNOW_M1_1.8_1_Smp': 'D_SNOW_1_1_1',
        'TA_M1_1.8_1_Smp': 'TA_M1_1.8_1_Smp',
        'QUALITY_iSR50AT_M1_1.8_1_Smp': 'QUALITY_iSR50AT_M1_1.8_1_Smp',
        'DIAG_iSR50AT_M1_1.8_1_Smp': 'DIAG_iSR50AT_M1_1.8_1_Smp'
    }

    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': False,
        'DATA_FREQUENCY': '1T',
        'DATA_HEADER_OUTPUT_TO_FILE': True,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': [],
        'DATA_HEADER_ROWS': [1, 2],  # 2022-01-05
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': False,
        'DATA_RENAME_COLUMNS': renaming_map,  # 2022-01-05
        'DATA_SEPARATOR': ',',
        'DATA_SKIP_ROWS': [3],  # 2022-05-01
        'DATA_TIMESTAMP_COL': 0,
        'DATA_TIMESTAMP_FORMAT': '%Y-%m-%d %H:%M:%S',  # 2022-01-05
        'DATA_TIMESTAMP_KEEP_NON_ICOS': True,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/15_meteo_snowheight'),
        'DIR_OUT_LOGFILE': Path('logs'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/15_meteo_snowheight'),
        'FILE_FILEGROUP': '15_meteo_snowheight',  # 2022-01-05
        'FILENAME_DAY_POSITION': [24, 26],  # 2022-01-05
        'FILENAME_FOR_ICOS': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [],
        'FILENAME_ID': 'CH-DAV_snowheight_*.dat',  # 2022-01-05
        'FILENAME_LENGTH': 30,
        'FILENAME_MINUTE_POSITION': [],
        'FILENAME_MONTH_POSITION': [22, 24],  # 2022-01-05
        'FILENAME_YEAR_POSITION': [18, 22],  # 2022-01-05
        'OUTFILE_COMPRESSION': True,
        'OUTFILE_DELETE_UNCOMPRESSED': True,
        'OUTFILE_ICOS_FILENUMBER_FN': '07',  # 2022-01-05
        'OUTFILE_ICOS_LOGGERNUMBER_LN': '01'
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\15_meteo_snowheight'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\15_meteo_snowheight')  # testing
    }

    # previous format ending 2021-12-01:
    # (deprecated) example filename: CH-Dav_BM_20211031_L01_F06.dat
    # 'DATA_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
    # 'DATA_HEADER_ROWS': [0],
    # 'DATA_RENAME_COLUMNS': False,
    # 'DATA_SKIP_ROWS': [],
    # 'FILENAME_YEAR_POSITION': [10, 14],
    # 'FILENAME_MONTH_POSITION': [14, 16],
    # 'FILENAME_DAY_POSITION': [16, 18],
    # 'FILENAME_ID': 'CH-Dav_BM_*_L01_F06.dat',
    # 'FILE_FILEGROUP': '10_meteo',
    # 'OUTFILE_ICOS_FILENUMBER_FN': '06',

    return file_info


def f_17_meteo_profile():
    # example filename: CH-Dav_BM_20180819_L01_F02.dat

    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': False,
        'DATA_FREQUENCY': '10S',
        'DATA_HEADER_OUTPUT_TO_FILE': True,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': [],
        'DATA_HEADER_ROWS': [0],
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': False,
        'DATA_RENAME_COLUMNS': False,
        'DATA_SEPARATOR': ',',
        'DATA_SKIP_ROWS': None,
        'DATA_TIMESTAMP_COL': 0,
        'DATA_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
        'DATA_TIMESTAMP_KEEP_NON_ICOS': True,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/17_meteo_profile'),
        'DIR_OUT_LOGFILE': Path('log'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/17_meteo_profile'),
        'FILE_FILEGROUP': '17_meteo_profile',
        'FILENAME_DAY_POSITION': [16, 18],
        'FILENAME_FOR_ICOS': 'CH-Dav_BM_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [],
        'FILENAME_ID': 'CH-Dav_BM_*_L01_F02.dat',
        'FILENAME_LENGTH': 30,
        'FILENAME_MINUTE_POSITION': [],
        'FILENAME_MONTH_POSITION': [14, 16],
        'FILENAME_YEAR_POSITION': [10, 14],
        'OUTFILE_COMPRESSION': True,
        'OUTFILE_DELETE_UNCOMPRESSED': True,
        'OUTFILE_ICOS_FILENUMBER_FN': '02',
        'OUTFILE_ICOS_LOGGERNUMBER_LN': '01'
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\17_meteo_profile'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\17_meteo_profile')  # testing
    }

    return file_info


def f_30_profile_ghg():
    file_info = {
        'DATA_COMPLEMENT_WITH_PREVIOUS_DATE': False,
        'DATA_FREQUENCY': '1S',
        'DATA_HEADER_OUTPUT_TO_FILE': True,
        'DATA_HEADER_REMOVE_SUFFIX_FROM_VARIABLE_NAMES': [],
        'DATA_HEADER_ROWS': [0],
        'DATA_ICOS_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
        'DATA_KEEP_ONLY_RENAMED_COLUMNS': False,
        'DATA_RENAME_COLUMNS': False,
        'DATA_SEPARATOR': ',',
        'DATA_SKIP_ROWS': None,
        'DATA_TIMESTAMP_COL': 0,
        'DATA_TIMESTAMP_FORMAT': '%Y%m%d%H%M%S',
        'DATA_TIMESTAMP_KEEP_NON_ICOS': True,
        'DIR_OUT_ICOS': Path('//grasslandserver.ethz.ch/processing/CH-DAV_Davos/01_ICOS_TRANSFER/30_profile_ghg'),
        'DIR_OUT_LOGFILE': Path('logs'),
        'DIR_SOURCE_FILES': Path('//grasslandserver.ethz.ch/archive/FluxData/CH-DAV_Davos/30_profile_ghg'),
        'FILE_FILEGROUP': '30_profile_ghg',
        'FILENAME_DAY_POSITION': [16, 18],
        'FILENAME_FOR_ICOS': 'CH-Dav_ST_{year}{month:02d}{day:02d}_L{logger}_F{file}.csv',
        'FILENAME_HOUR_POSITION': [],
        'FILENAME_ID': 'CH-Dav_ST_*_L10_F01.dat',
        'FILENAME_LENGTH': 30,
        'FILENAME_MINUTE_POSITION': [],
        'FILENAME_MONTH_POSITION': [14, 16],
        'FILENAME_YEAR_POSITION': [10, 14],
        'OUTFILE_COMPRESSION': True,
        'OUTFILE_DELETE_UNCOMPRESSED': True,
        'OUTFILE_ICOS_FILENUMBER_FN': '02',  # renamed to correct ICOS file number
        'OUTFILE_ICOS_LOGGERNUMBER_LN': '10'
        # 'DIR_SOURCE_FILES': Path(r'F:\Downloads\_temp\testing_ppicos\input\30_profile_ghg'),  # testing
        # 'DIR_OUT_ICOS': Path(r'F:\Downloads\_temp\testing_ppicos\output\30_profile_ghg')  # testing
    }

    return file_info
